### PR TITLE
Added benchmark_catkin to dependencies

### PR DESCRIPTION
**Pull request by eggerk**

### CODE REVIEW

**Comment by mfehr** [comment]
You will need to remove benchmark_catkin from dependencies, can you open the PR for this as well, so we can merge them at the same time?

**Comment by eggerk** [comment]
It will be removed in here: https://github.com/ethz-asl/maplab_private/pull/816

**Comment by mfehr** [comment]
@eggerk great, I will force-merge them both, ok?

**Comment by eggerk** [comment]
ok, good for me

**Comment by mfehr** [comment]
@eggerk done, could you run a full build-test of maplab_private to verify everything is in order now?

**Comment by eggerk** [comment]
Running here: https://jenkins.asl.ethz.ch/view/maplab/job/maplab_private_pull_requests/1842/

**Comment by eggerk** [comment]
Build succeeded: https://jenkins.asl.ethz.ch/view/maplab/job/maplab_private_pull_requests/1842/

**Pull request merged**
